language: python
python:
  - "3.6"
  
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  
install:
  - conda env create -f conda.yml
  - python download_weights.py
  
script:
  - python -m unittest discover -s tests
